package gui;

import backend.Administrador;
import backend.Loja;
import backend.RepositorioLojas;
import backend.Sistema;
import backend.Subscricao;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

/**
 *
 * @author Adão Teixeira, Cláudia Ribeiro, José Ribeiro
 *
 */
public class JanelaLogin extends JDialog {

    private Sistema sistema;
    private JanelaPrincipal principal;

    public JanelaLogin(Sistema sistema, JanelaPrincipal principal) {

        initComponents();

        this.sistema = sistema;

        this.principal = principal;

        //Configurações da janela
        this.setTitle("Atenticar");
        this.setModal(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);

        textFieldUtilizador.requestFocus();

    }

    public void autenticar() {
        if (textFieldUtilizador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Intruduza p.f. o username!");
            textFieldUtilizador.requestFocus();
            return;
        }

        if (passwordField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Intruduza p.f. a sua password!");
            passwordField.requestFocus();
            return;
        }

        if (!sistema.autenticarUtilizador(textFieldUtilizador.getText().toLowerCase(), new String(passwordField.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Utilizador inválido.",
                    "Autenticação", JOptionPane.WARNING_MESSAGE);
            textFieldUtilizador.requestFocus();
        } else {
            if (sistema.getUtilizadorLigado() instanceof Administrador) {
                principal.menuAdmin();
                dispose();
            } else {
                try {
                    Loja lojaLigada = sistema.getRepositorioLojas().getLojaByUsername(sistema.getUtilizadorLigado().getUsername());
                    if (lojaLigada.getSubscricao().equals(Subscricao.PENDENTE)) {
                        JOptionPane.showMessageDialog(principal, "Os produtos não estão visiveis pois a sua subscrição esta pendente!",
                                "Subscrição", JOptionPane.WARNING_MESSAGE);
                    } else if (lojaLigada.getSubscricao().equals(Subscricao.SUSPENSA)) {
                        JOptionPane.showMessageDialog(principal, "Os produtos não estão visiveis pois a sua subscrição esta suspensa!\n Para ativar a sua subscrição compre um novo pacote de cliques!",
                                "Subscrição", JOptionPane.WARNING_MESSAGE);
                    } else if (lojaLigada.getNumeroCliquesAtuais() < 50) {
                        JOptionPane.showMessageDialog(principal, " A sua loja apenas possui " + lojaLigada.getNumeroCliquesAtuais() + " cliques! \n Para continuar a mostrar os seu produtos, por favor, proceda a compra de um novo pacote.",
                                "Subscrição", JOptionPane.WARNING_MESSAGE);
                    }
                    principal.menuLoja(lojaLigada);
                    dispose();
                } catch (RepositorioLojas.LojaNaoExisteException ex) {
                    JOptionPane.showMessageDialog(this, "Loja não Existe",
                            "Autenticação", JOptionPane.WARNING_MESSAGE);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        buttonAutenticar = new javax.swing.JButton();
        buttonTerminar = new javax.swing.JButton();
        textFieldUtilizador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autentificação");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelUsername.setText("Username:");

        labelPassword.setText("Password:");

        buttonAutenticar.setText("Autenticar");
        buttonAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAutenticarActionPerformed(evt);
            }
        });

        buttonTerminar.setText("Terminar");
        buttonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelUsername)
                    .addComponent(labelPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAutenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAutenticarActionPerformed
        autenticar();
    }//GEN-LAST:event_buttonAutenticarActionPerformed

    private void buttonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTerminarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonTerminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAutenticar;
    private javax.swing.JButton buttonTerminar;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldUtilizador;
    // End of variables declaration//GEN-END:variables
}
