package gui;

import backend.Loja;
import backend.Sistema;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

/**
 *
 * @author Adão Teixeira, Cláudia Ribeiro, José Ribeiro
 *
 */

public class JanelaCompraCliques extends JDialog {

    private int cliques;
    private Sistema sistema;
    private Loja lojaLigada;

    public JanelaCompraCliques(Sistema sistema, Loja lojaLigada) {
        initComponents();
        this.sistema = sistema;
        this.lojaLigada = lojaLigada;

        //Configurações da janela
        this.setTitle(lojaLigada.getNome() + " | Comprar cliques");
        this.setModal(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);

        //Colocar a informação sobre a loja e os seus cliques
        labelColocarNomeLoja.setText(lojaLigada.getNome());
        labelColocarCliquesAtuais.setText(String.valueOf(lojaLigada.getNumeroCliquesAtuais()));
        labelColocarCliquesUtilizados.setText(String.valueOf(lojaLigada.getNumeroCliquesUtilizados()));

    }
    
    //Adiciona um pedido de cliques á loja
    public void comprarCliques() {
        if (!checkBox100Cliques.isSelected() && !checkBox200Cliques.isSelected() && !checkBox300Cliques.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione p.f. um pacote de cliques!");
            return;
        } else if (lojaLigada.getPedidoCliques() != 0) {
            JOptionPane.showMessageDialog(this, "Não é possível comprar mais cliques pois a sua loja possui um pedido pendente!");
            return;
        }
        lojaLigada.setPedidoCliques(cliques);
        JOptionPane.showMessageDialog(this, "O seu pedido foi registado, por favor, aguarde a sua validação. \n Obrigado.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonComprar = new javax.swing.JButton();
        buttonTerminar = new javax.swing.JButton();
        checkBox100Cliques = new javax.swing.JCheckBox();
        labelPacotesCliques = new javax.swing.JLabel();
        checkBox200Cliques = new javax.swing.JCheckBox();
        checkBox300Cliques = new javax.swing.JCheckBox();
        labelNome = new javax.swing.JLabel();
        labelCliquesAtuais = new javax.swing.JLabel();
        labelColocarNomeLoja = new javax.swing.JLabel();
        labelColocarCliquesAtuais = new javax.swing.JLabel();
        labelColocarCliquesUtilizados = new javax.swing.JLabel();
        labelCliquesUtilizados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(25, 25));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonComprar.setText("Comprar");
        buttonComprar.setToolTipText("");
        buttonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComprarActionPerformed(evt);
            }
        });

        buttonTerminar.setText("Terminar");
        buttonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTerminarActionPerformed(evt);
            }
        });

        checkBox100Cliques.setText("100 Cliques");
        checkBox100Cliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox100CliquesActionPerformed(evt);
            }
        });

        labelPacotesCliques.setText("Selecione um Pacote Cliques:");

        checkBox200Cliques.setText("200 Cliques");
        checkBox200Cliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox200CliquesActionPerformed(evt);
            }
        });

        checkBox300Cliques.setText("300 Cliques");
        checkBox300Cliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox300CliquesActionPerformed(evt);
            }
        });

        labelNome.setText("Nome Loja:");

        labelCliquesAtuais.setText("Número Cliques Atuais:");

        labelCliquesUtilizados.setText("Número de visitas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBox100Cliques)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBox200Cliques)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBox300Cliques)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(buttonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelColocarNomeLoja))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliquesAtuais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelColocarCliquesAtuais))
                            .addComponent(labelPacotesCliques)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliquesUtilizados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelColocarCliquesUtilizados)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelColocarNomeLoja))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCliquesAtuais)
                    .addComponent(labelColocarCliquesAtuais))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliquesUtilizados)
                    .addComponent(labelColocarCliquesUtilizados))
                .addGap(29, 29, 29)
                .addComponent(labelPacotesCliques)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox100Cliques)
                    .addComponent(checkBox200Cliques)
                    .addComponent(checkBox300Cliques)
                    .addComponent(buttonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprarActionPerformed
        comprarCliques();
    }//GEN-LAST:event_buttonComprarActionPerformed

    private void buttonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTerminarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonTerminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void checkBox100CliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox100CliquesActionPerformed
        if (checkBox200Cliques.isSelected() | checkBox300Cliques.isSelected()) {
            JOptionPane.showMessageDialog(this, "Apenas pode selecionar um pacote de cliques");
            checkBox100Cliques.setSelected(false);
            checkBox200Cliques.setSelected(false);
            checkBox300Cliques.setSelected(false);
        } else {
            cliques = 100;
        }
    }//GEN-LAST:event_checkBox100CliquesActionPerformed

    private void checkBox200CliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox200CliquesActionPerformed
        if (checkBox100Cliques.isSelected() | checkBox300Cliques.isSelected()) {
            JOptionPane.showMessageDialog(this, "Apenas pode selecionar um pacote de cliques");
            checkBox100Cliques.setSelected(false);
            checkBox200Cliques.setSelected(false);
            checkBox300Cliques.setSelected(false);
        } else {
            cliques = 200;
        }
    }//GEN-LAST:event_checkBox200CliquesActionPerformed

    private void checkBox300CliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox300CliquesActionPerformed
        if (checkBox100Cliques.isSelected() | checkBox200Cliques.isSelected()) {
            JOptionPane.showMessageDialog(this, "Apenas pode selecionar um pacote de cliques");
            checkBox100Cliques.setSelected(false);
            checkBox200Cliques.setSelected(false);
            checkBox300Cliques.setSelected(false);
        } else {
            cliques = 300;
        }
    }//GEN-LAST:event_checkBox300CliquesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComprar;
    private javax.swing.JButton buttonTerminar;
    private javax.swing.JCheckBox checkBox100Cliques;
    private javax.swing.JCheckBox checkBox200Cliques;
    private javax.swing.JCheckBox checkBox300Cliques;
    private javax.swing.JLabel labelCliquesAtuais;
    private javax.swing.JLabel labelCliquesUtilizados;
    private javax.swing.JLabel labelColocarCliquesAtuais;
    private javax.swing.JLabel labelColocarCliquesUtilizados;
    private javax.swing.JLabel labelColocarNomeLoja;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPacotesCliques;
    // End of variables declaration//GEN-END:variables
}
